export const loginRoute = "/login"
export const homeRoute = "/"
export const registerRoute = "/register"
export const resetPasswordRoute = "/reset-password"
export const verifyRoute = "/verify"
export const successRoute = "/success"
export const logoutRoute = "/logout"
export const dashboardRoute = "/dashboard"
export const businessRoute = "/business"
export const userManagementRoute = "/user-management"
export const marketplaceRoute = "/marketplace"
export const serviceManagementRoute = "/service-management"
export const deliveryManagementRoute = "/delivery-management"
export const communicationRoute = "/communication"
export const disputesManagementRoute = "/disputes-management"
export const reportAndAnalyticsRoute = "/analytics"
export const financeManagementRoute = "/finance-management"

    